#!/usr/bin/env bash
# uploads a file to a server

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

scp -o StrictHostKeyChecking=no "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
